services:
  database_server:
    image: postgres:latest
    container_name: database_server
    hostname: database_server
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.sample
    ports:
      - 5432:5432
