name: Publish container images to GHCR

on:
  workflow_run:
    workflows: ["Automated version release Schedule"]
    types:
      - completed
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  BuildPushImageGHCR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code repository
        id: code_checkout
        uses: actions/checkout@v4

      - name: Log in Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # trail
      - name: Extract tag name
        run: echo "${{ github.ref }}" | sed 's/refs\/tags\///' > .version

      - name: Display version
        run: cat .version

      - name: Extract Docker metadata
        id: extract_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=sha
            type=edge
            type=ref,event=pr
            type=sha,format=long
            type=ref,event=branch
            type=semver,pattern=v{{major}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=schedule,pattern={{date 'YYYYMMDD' tz='Asia/Dhaka'}}

      - name: Build and push Docker image
        id: build_push_image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.extract_meta.outputs.tags }}
          labels: ${{ steps.extract_meta.outputs.labels }}
