name: Automated version release Schedule

on:
  push:
    branches:
      - main

# on:
#   pull_request:
#     types:
#       - closed

jobs:
  AutomatedRelease:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code repository
        id: code_checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Releasing new version with Python semantic release
        id: release_version
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
