name: Extract Docker Metadata

on:
  push:

jobs:
  extract_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Metadata Action
        uses: docker/metadata-action@v5
        id: extract_meta
        with:
          images: |
            ${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}

      - name: Display extracted metadata
        run: |
          echo "Tags: ${{ steps.extract_meta.outputs.tags }}"
          echo "Labels: ${{ steps.extract_meta.outputs.labels }}"
