name: Extract Docker Metadata

on:
  push:

jobs:
  extract_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: latest_tag
        uses: JinoArch/get-latest-tag@latest

      - name: Display extracted metadata
        run: |
          echo "Working Latest tag: ${{ steps.latest_tag.outputs.latestTag }}"

      - name: Set up Docker Metadata Action
        uses: docker/metadata-action@v5
        id: extract_meta
        with:
          images: |
            ${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}

      - name: Display extracted metadata
        run: |
          echo "Tags: ${{ steps.extract_meta.outputs.tags }}"
          echo "Labels: ${{ steps.extract_meta.outputs.labels }}"
