name: Extract Docker Metadata

on:
  release:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  extract_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Metadata Action
        uses: docker/metadata-action@v5
        id: extract_meta
        with:
          context: git
          flavor: latest=auto
          images: |
            ${{ github.repository }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=sha,prefix=,format=short
            type=semver,pattern=v{{major}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule,pattern={{date 'YYYYMMDD' tz='Asia/Dhaka'}}

      - name: Display extracted metadata
        run: |
          echo "Tags: ${{ steps.extract_meta.outputs.tags }}"
          echo "Labels: ${{ steps.extract_meta.outputs.labels }}"
          echo "------"
          echo "${{ github.ref }}"
